#!/bin/bash
#
#see skript tuvastab kas sisestatud arv on paarisarv
#
read -p "palun sisestage siia t2isarv: " arv
if (( $arv % 2 == 0 ))
then
echo "see on paaris arv"
else
echo "see on paaritu arv"
fi
#
#
#skripti l6pp
