#!/bin/bash
#
# yl2 t66k2su t2itmine
#
echo "Hans Arvet Tilk" # Minu nimi
echo "6pin ISP118 IT-systeemide nooremspetsialistiks" # kelleks ma 6pin ja mis 6ppegrupis
echo "See aine 6petab v2ga palju" # Kuidas mulle tundub see aine
echo "Muljed on head ja motivatsioon pole 2ra l2inud, uued asjad tulevad peale ja tahan neid 6ppida" # minu praegune mulje ja edasij6udmine jne
#
# skriptimisl6pp
