#!/bin/bash
#
# kysib kasutaja k2est tema nime ja tervitab teda
# 
echo -n "Tere! sisestage oma ees- ja perenimi: " # kysib nime
read eesnimi perenimi # loeb nime
echo "Tere tulemast $eesnimi $perenimi" # tervitab kylastajat
#
# skriptimise l6pp
